### ISSUE TITLE
Running script on pi

### ISSUE THREAD

**Issue by piechade** [loblab/noip-renew#1]
I getting the following message:

Package chromedriver is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'chromedriver' has no installation candidate

**Comment by loblab** [comment]
Yes. I ever tried it on Pi, same issue. However, I didn't deploy it on Pi finally.

Maybe you can try this: https://www.raspberrypi.org/forums/viewtopic.php?t=206439

Another choice is to run docker on Pi :)

**Comment by piechade** [comment]
I modified the script and it's work, need to wait if my domain is renewable.
