### ISSUE TITLE
Better feedback with pushover notifications - not an issue more a feature reuquest

### ISSUE THREAD

**Issue by requa3r0** [loblab/noip-renew#10]
Hi lollab.

I have added this python function to my code

The function is insearted as the first function in 
class Robot:

>     def pushover(self, msg):
>         conn = httplib.HTTPSConnection("api.pushover.net:443")
>         conn.request("POST", "/1/messages.json",
>         urllib.urlencode({
>         "token": "mypushovertoken",
>         "user": "mypushoveruserkey",
>         "message": msg,
>         "device": "SOMEDEVICENAME",    #OPTIONAL switch.....but i like to have this messate send only to a specific device
>         }), { "Content-type": "application/x-www-form-urlencoded" })
>         conn.getresponse()

Its activated here.

>         for button in buttons_todo:
>             button.click()
>             time.sleep(1)
>         self.browser.save_screenshot("result.png")
>         self.log_msg("Confirmed hosts: %d" % count, 2)
> 
>         #pushover
>         if count > 0:
>                 self.pushover("Confirmed hosts: %d" % count)
>         return True

The user will receive a pushover notification on his smartphone with the pushover app, with info about number of host confirmed.

Very handy im my opionion.

You could add the pushover info and activation switch in the .sh script with other credientials.

Keep up the good work

Requaero.

**Comment by loblab** [comment]
Hi @requa3r0,

Thank you for the suggestion & code. However, I don't think it is a core function of the script. Different users may need different notifications. Just keep it simple. Thanks.

**Comment by loblab** [comment]
For the users need notifications, please try the branch of @IDemixI 
https://github.com/IDemixI/noip-renew/tree/notifications
