### ISSUE TITLE
能否在脚本中加入参数，让chromedriver使用http代理

### ISSUE THREAD

**Issue by ivybridgei** [loblab/noip-renew#11]
脚本在墙外还是不错的，墙内老是timeout，有没有让chromedriver使用http代理的方法？

**Comment by loblab** [comment]
代码里是加了的。设置一个环境变量https_proxy。这个能用吗？
```python
        if 'https_proxy' in os.environ:
            options.add_argument("proxy-server=" + os.environ['https_proxy'])
```
然而，http代理能做T？

**Comment by ivybridgei** [comment]
> 代码里是加了的。设置一个环境变量https_proxy。这个能用吗？
> 
> ```python
>         if 'https_proxy' in os.environ:
>             options.add_argument("proxy-server=" + os.environ['https_proxy'])
> ```
> 
> 然而，http代理能做T？

v2ray、clash之类可以开http代理的，不过刚才我试了一下把timeout的值从60调到300，不再返回timeout了，所以我暂时不准备用代理了。

**Comment by loblab** [comment]
OK
