### ISSUE TITLE
Exception: Incorrect padding

### ISSUE THREAD

**Issue by auto-mation** [loblab/noip-renew#15]
Hi,
i am getting the following error when trying to renew:

2020/04/12 14:29:49 [xxx@gmail.com] - Debug level: 2
2020/04/12 14:29:49 [xxx@gmail.com] - Opening https://www.noip.com/login...
2020/04/12 14:29:50 [xxx@gmail.com] - Logging in...
2020/04/12 14:29:50 [xxx@gmail.com] - Exception: Incorrect padding

**Comment by IDemixI** [comment]
Hi @auto-mation , which version of the script are you using? The latest commit? The error in question happens when the password stored in the noip-renew.sh file isn’t in base64. If you pulled this script over an older installation then perhaps the noip-renew.sh file is still the old one which doesn’t contain your No-IP password in base64. Sorry about that, anyway. I think I need to adjust the installation to make sure it removes an older one first. 

Let me know how you get on with the above, anyway!

**Comment by auto-mation** [comment]
now i am getting Exception: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="clogs"]"}
  (Session info: headless chrome=80.0.3987.163)

**Comment by auto-mation** [comment]
I am actually getting this now, progress i guess...


2020/04/12 15:30:52 [xxx@gmail.com] - Debug level: 2
2020/04/12 15:30:52 [xxx@gmail.com] - Opening https://www.noip.com/login...
2020/04/12 15:30:53 [xxx@gmail.com] - Logging in...
2020/04/12 15:30:57 [xxx@gmail.com] - Opening https://my.noip.com/#!/dynamic-dns...
2020/04/12 15:30:57 [xxx@gmail.com] - Updating hosts...
2020/04/12 15:30:58 [xxx@gmail.com] - Unable to find the buttons...
2020/04/12 15:30:59 [xxx@gmail.com] - Unable to find the buttons...
2020/04/12 15:31:00 [xxx@gmail.com] - Unable to find the buttons...
2020/04/12 15:31:01 [xxx@gmail.com] - Unable to find the buttons...
2020/04/12 15:31:02 [xxx@gmail.com] - Unable to find the buttons...
2020/04/12 15:31:02 [xxx@gmail.com] - Invalid page or something wrong. See error.png

**Comment by IDemixI** [comment]
Hi @auto-mation , Thank you for the feedback. I've come across this before but after running the script again it seemed to disappear. That is an odd one! Could you please post your error.png so I can take a look which page it's actually on when this occurs?

This looks to be something to do with "xpath_of_button" not firing correctly or firing too early.

I'm working on another update to this script to stop any of these kinds of issues from cropping up, so hopefully, that resolves the issue. I'm really sorry about that. I should have it up by later today.

In the meantime, I'm happy to try and troubleshoot this.

**Comment by IDemixI** [comment]
This should be resolved in my latest pull request (v 0.9). #16

**Comment by loblab** [comment]
@auto-mation Please try the latest version (v 0.9), with IDemixI's update merged.

@IDemixI Thank you.

**Comment by auto-mation** [comment]
that solved the issue, thanks! @IDemixI and @loblab :)
