### ISSUE TITLE
Problem with 0.9

### ISSUE THREAD

**Issue by robustini** [loblab/noip-renew#18]
I've very old version 0.4 and work fine on RPI3.
With 0.9 i've this error:

  File "/usr/local/bin/noip-renew.py", line 35
    print(f"[{self.time_string_formatter}] - {msg}")
                                                  ^
SyntaxError: invalid syntax

**Comment by IDemixI** [comment]
Hi @robustini ,

This error indicates your version of Python is below 3.6. The new setup.sh with this script should detect this and prompt you to update Python version. To check which version of Python is running, you can type `python3 --version` to see what you're running.

I hope this helps! I'm running the script on an RPI2 if that helps.

**Comment by robustini** [comment]
Hi @IDemixI , i've Python V3.8 installed now, the problem is the same.

**Comment by IDemixI** [comment]
Hi @robustini ,

Sorry for the delay in getting back to you. I believe that the "Shebang" line at the top of the script will still be pointing to your older version of Python 3, as it's an altinstall - If you followed that link. 

If you type `python3 --version` it will probably still say your old version.

What you need to do is to change the Shebang line (line 1 of noip-renew.py) as follows:
Currently: `#!/usr/bin/env python3`
Change to: `#!/usr/bin/env python3.8`

That should sort it.

Sorry for any confusion with this. I thought I was future-proofing the script by making it use a newer python and using f strings which are great, but as seen here, a lot of people are still using an earlier version of Python than 3.6 by default. 

Please let me know how the above goes for you.

Thanks
Ryan

**Comment by robustini** [comment]
Hi @IDemixI , reinstalled now with the change in the first line of noip-renew.py, now the error is this one:

Traceback (most recent call last):
  File "/usr/local/bin/noip-renew.py", line 16, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'


But selenium is installed:

Requirement already satisfied: selenium in /usr/local/lib/python3.5/dist-packages
Requirement already satisfied: urllib3 in /usr/local/lib/python3.5/dist-packages (from selenium)

**Comment by IDemixI** [comment]
Hi @robustini 

It looks like we're almost there. So this is because Selenium is installed against your older version of python (3.5).

One more adjustment needs to be made, unfortunately.

So in setup.sh there is the following on line 50:
`$SUDO $PYTHON -m pip install selenium`
Please change it to:
`$SUDO python3.8 -m pip install selenium`

After installing again this should work. I've just compiled python 3.8 on my pi (took around 7 hours on the raspberry pi 2 b+ haha). Running it myself now using those two small changes.

So that's the Shebang line change in the script itself, and the small change to the setup.sh.

Many thanks!
Ryan

**Comment by robustini** [comment]
All aligned, all installed and updated, and now:

  File "/usr/local/bin/noip-renew.py", line 35
    print(f"[{self.time_string_formatter}] - {msg}")
                                                  ^
SyntaxError: invalid syntax

I'm desperate! :-)

**Comment by robustini** [comment]
No, my wrong, all work fine now!
