### ISSUE TITLE
no hosts or host table rows not found

### ISSUE THREAD

**Issue by LordDarkneo** [loblab/noip-renew#25]
Hi again!
I keep moving forward and once again thanks for your help!

I am now facing this issue (the script does not connect) and after checking the files, I am almost sure that is because my pwd contains special characters ($, !, /, etc...).

Regards

edit: In fact does not seem to linked to special char... I changed the pwd and faced the same issue (debug1 showing login page, debug 2 showing user/pwd combination is incorrect). The script reports asuccessful connection btw:

> pi@octopi:~/noip-renew $ ./noip-renew.sh
> [2020/06/27 15:38:04] - Debug level: 2
> [2020/06/27 15:38:04] - Opening https://www.noip.com/login...
> [2020/06/27 15:38:08] - Logging in...
> [2020/06/27 15:38:15] - Opening https://my.noip.com/#!/dynamic-dns...
> [2020/06/27 15:38:18] - No hosts or host table rows not found
> 30 0    * * *   pi    /usr/local/bin/noip-renew-pi /var/log/noip-renew/pi

**Comment by IDemixI** [comment]
Hi @LordDarkneo, 

Could be an issue with the details missing from noip-renew.sh. Special characters are fine in the password as far as I'm aware.

So when you install the script and it asks for user details, these then get stored in `/usr/local/bin/noip-renew-pi`.
The username is in plain text in this file, while the password is converted to base64, so it's not stored in plain text.

When you run the `noip-renew-pi` command it calls the script (`/usr/local/bin/noip-renew.py`) using those details from `/usr/local/bin/noip-renew-pi` and decodes the base64 before passing it through to selenium. Somewhere along the road it's dropping your details. 

Realistically the script should check for a failed login and report back, making it easier to debug, but unfortunately, I don't have any time to sort that at the moment.

anyway, please make sure that your details are correct in  `/usr/local/bin/noip-renew-pi` - If you're curious regarding the pass you can even copy and paste it out to an online base64 decoder to make sure you've entered it correctly.

Ta!
Ryan

**Comment by LordDarkneo** [comment]
Hi!
Damn, I was planing to send a complete message to detail my tests... And I finally got what is wrong... the installation manual (I think).
From the tests performed and the code I have parsed with your explanation, when running the command `./noip-renew.sh` will surely fall into error... As it is missing parameters to connect!
So the step 3 in the installation manual should be changed either to : 
- try the connection with ./noip-renew.sh "user" "pwd" 2 (to have the debug level set to 2)
- run the noip-renew-pi command

**Comment by IDemixI** [comment]
@LordDarkneo,

I admit that step isn’t too clear. To run the script outside of the scheduled task, you need to run it via /usr/local/bin/noip-renew-pi 
No parameters required. 

Anything stored in /usr/local/bin can be accessed by just tying the “command” into terminal. So to access that above script you literally type `noip-renew-pi` - as long as you set up the user correctly during installation, the script would run properly. 

I hope you’ve managed to get things running properly now anyway.

Thanks
Ryan

**Comment by LordDarkneo** [comment]
Hi,
Yes everything seems fine know! And the point is not about the command noip-renew-pi and where you execute it, but the noip-renew.sh in step 3. 
I think you just need to modify the step 3, and change the noip-renew.sh by noip-renew-pi
Anyway thanks for help and support ;)

**Comment by GilDev** [comment]
Thanks! Definitely would need some clarification, I was just running `noip-renew.sh` and got the same error without knowing why.
