### ISSUE TITLE
Why has the crontab been moved out of the docker container?

### ISSUE THREAD

**Issue by Eldiabolo21** [loblab/noip-renew#26]
Hi everyone, 

I just pulled the latest version and realized, that for Docker usage, the docker-compose and Dockerfile have changed. As far as i understand it, it is intended that the crontab is run on the Dockerhost, which executes a `docker exec` to run the update script inside the container. Why has this implementation been choose? 

This goes completely against the docker concept. When I run `docker-compose up` I want everything that is related and neccessary for that container to be in there as well as all of it removed when I run `docker-compose down` 

Cheers
Fabian

**Comment by fkahhaleh** [comment]
Hi Fabian,
I second that. Personally I ran through some issues and have not yet gotten the docker container to be fully working as it should.
Besides the external crontab entry, I am having problems with 'sudo' not being installed, cron not being installed as well as getting proper access to change /etc/crontab in the script even when 'sudo' is installed.

Not sure if I am missing something or not, but I did try several things and it would almost seem easier for me to build a new base image all together.

Did you run into any similar issues?

F.K

**Comment by Callum17** [comment]
I actually wondered why it is being run via exec + docker-compose service in the first place. Is there a reason why we can't simply have standalone docker image?

See "usage with docker" in the readme:
https://github.com/Callum17/noip-renew
https://github.com/loblab/noip-renew/pull/29/commits

**Comment by Eldiabolo21** [comment]
> Hi Fabian,
> I second that. Personally I ran through some issues and have not yet gotten the docker container to be fully working as it should.
> Besides the external crontab entry, I am having problems with 'sudo' not being installed, cron not being installed as well as getting proper access to change /etc/crontab in the script even when 'sudo' is installed.
> 
> Not sure if I am missing something or not, but I did try several things and it would almost seem easier for me to build a new base image all together.
> 
> Did you run into any similar issues?
> 
> F.K

Yeah, I doesnt really work for me either when i try to build it. But as i wont install the crontab on my dockerhost, i didnt bother too much with it. thinking of forking this and doing it properly. Havent gotten around just yet.

**Comment by IDemixI** [comment]
Hi guys,

Sorry I didn’t change any of the docker stuff as the script evolved. I’m actually not familiar with docker in the slightest (something I need to change..) so all changes I made to the script from like 0.6 upwards didn’t factor the docker files in at all. For example, I see that number of hosts is still being used somewhere? But I updated the script itself to not need that anymore. 

Anyway, good luck getting the docker part of this up to scratch! If you have any questions about the script itself, please feel free to ask and if I can answer I will. I’ve been pretty busy lately and as such I called it a day with the contributions to this script, so I’m a tad rusty on everything.

Cheers
Ryan

**Comment by fkahhaleh** [comment]
Hi Ryan, 
Thanks for the feedback. I guess it makes sense now why we re having an issue.
I am completely new to Docker myself.

Eldiabolo21, if you get it, please fork or PR. I am also going to find sometime to make something perhaps I can get it.

Thanks @Callum17  for that PR. will use it perhaps as a base for my changes!

Great script all... much appreciated.

Fadi

**Comment by dannypv05261** [comment]
> I actually wondered why it is being run via exec + docker-compose service in the first place. Is there a reason why we can't simply have a standalone docker image?
> 
> See "usage with docker" in the readme:
> https://github.com/Callum17/noip-renew
> https://github.com/loblab/noip-renew/pull/29/commits

That makes sense. The project is simple by just running a py file. docker-compose may overkill the project.
Also, the script just needs to run a few times per week. It is a good idea to run the docker container when the scheduled time reaches.

I have copied your DockerFile. After removing few lines of code about running noip-renew-skd.sh inside that py file, this solution works well for me. Thanks @Callum17.

It seems that the author intends to keep a Debian machine running with docker, execute the program inside that long-running container / keep a crontab within that container.

**Comment by loblab** [comment]
Merged PR of @Callum17 . thanks.
