### ISSUE TITLE
Fail to set password with setup.sh

### ISSUE THREAD

**Issue by yanuck** [loblab/noip-renew#28]
Hello,

I am trying to run your script on FreeBSD..
Everything going well, till i try to set my NOIP password by using setup.sh, here the error i get :
![error](https://user-images.githubusercontent.com/10265403/87708891-6badb700-c771-11ea-8c19-fbea9feccb32.png)

**Comment by IDemixI** [comment]
Hmm that could be a legitimate bug. I will try and investigate if I get some time. Have you tried completely removing the script and running the setup.sh again? If you set your No-IP details during installation it should work. I have a feeling I know why this isn’t working... the idiot that coded that bit didn’t test it ;P - that would be me... haha. Sorry about that! But yeah, setting those details during installation should work fine. I don’t think I actually added any checks to see if firstly the file exists if you straight away try to add the No-IP details and secondly I think it’s looking for an empty string so if you previously added the details it will fall over (which is what I believe has happened here).
Thanks
Ryan

**Comment by kevinpatrickkent** [comment]
I get a similar error as well when I try to set the username and password:

sed: can't read /usr/local/bin/noip-renew-XXXXXXXX: No such file or directory

XXXXXXXXX above is my username

**Comment by kevinpatrickkent** [comment]
I completely removed the script as suggested and ran setup.sh again and that fixed this problem for me!
