### ISSUE TITLE
installing on pi?

### ISSUE THREAD

**Issue by johnnyt83** [loblab/noip-renew#4]
hi loblab,
thanks for your great script. could you give a short tutorial on how to install this on a pi?
that would be awesome!

**Comment by robustini** [comment]
Same request, thanks!

**Comment by thangvc91** [comment]
same request :), it seems that can not use for pi, because chromedriver didn't release for ARMHF.

**Comment by thangvc91** [comment]
hello , 
I already install chromedriver on my Raspberry Pi 3B+, but when i tried to run ./setup.sh , it show error as below, do anybody has any advise for me in this case ? it seems that the system can not identify chromedriver ? 

![error](https://user-images.githubusercontent.com/28442911/58367245-5e978e00-7f07-11e9-9863-a648c3010cd9.jpg)

**Comment by robustini** [comment]
> 
> 
> hello ,
> I already install chromedriver on my Raspberry Pi 3B+, but when i tried to run ./setup.sh , it show error as below, do anybody has any advise for me in this case ? it seems that the system can not identify chromedriver ?
> 
> ![error](https://user-images.githubusercontent.com/28442911/58367274-a0283900-7f07-11e9-88c1-09f56c052d6a.jpg)

Same here...

**Comment by dj-bulka** [comment]
For those who are using Pi 3B+ hardware, solution is very simple, just edit 'setup.sh' file and replace below line:

`$SUDO apt -y install chromedriver`

with line:

`$SUDO apt -y install chromium-chromedriver`

There is no Chrome yet on RasPi, it's using Chromium browser, so the Driver package name differs.
Also I recommend to upgrade 'chromium-browser' package so they match.

It's working for me.

**Comment by robustini** [comment]
> 
> 
> For those who are using Pi 3B+ hardware, solution is very simple, just edit 'setup.sh' file and replace below line:
> 
> `$SUDO apt -y install chromedriver`
> 
> with line:
> 
> `$SUDO apt -y install chromium-chromedriver`
> 
> There is no Chrome yet on RasPi, it's using Chromium browser, so the Driver package name differs.
> Also I recommend to upgrade 'chromium-browser' package so they match.
> 
> It's working for me.

Work fine, thanks!

**Comment by sandeepan0403** [comment]
I managed to get it installed on the raspberry pi 3+ however I get the following message and no error or confirmation log gets created? Anyone have the same issue?

pi@pivpn:~/noip/noip-renew $ sudo ./noip-renew.sh
Traceback (most recent call last):
  File "./noip-renew.py", line 138, in <module>
    sys.exit(main())
  File "./noip-renew.py", line 134, in main
    robot = Robot(debug)
  File "./noip-renew.py", line 39, in __init__
    self.browser = webdriver.Chrome(chrome_options=options)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created
from disconnected: unable to connect to renderer
  (Session info: headless chrome=74.0.3729.157)
  (Driver info: chromedriver=74.0.3729.157 (7b16107ab85c5364cdcd0b2dea2539a1f2dc327a-refs/branch-heads/3729@{#998}),platform=Linux 4.19.57-v7+ armv7l)

**Comment by drunkly** [comment]
When I install and run on raspberry got this:
`$ ./noip-renew.sh
Traceback (most recent call last):
  File "./noip-renew.py", line 16, in <module>
    from selenium import webdriver
ImportError: No module named selenium
`
I could solve it running:
`sudo pip install selenium`

maybe setup.sh on line 32 should be like this?:
$SUDO pip install selenium

Thanks for the script, besides this minor issue, all is working as expected by now :)

**Comment by sandeepan0403** [comment]
Are you running this on an raspberry pi 3+? Did you have to install anything else? I still get the same error message as above sadly.

**Comment by drunkly** [comment]
I have installed on Raspberry Pi 2 (Raspbian)
The only things I have a changed are the chromium driver (as suggested above) and selenium installation:
sudo apt -y install chromedriver
sudo pip install selenium

I recommend also you check pip and pip3 are installed before install selenium:
sudo apt-get -y install pip pip3

That was all I did and it's running by now.

**Comment by drunkly** [comment]
> I managed to get it installed on the raspberry pi 3+ however I get the following message and no error or confirmation log gets created? Anyone have the same issue?
> 
> pi@pivpn:~/noip/noip-renew $ sudo ./noip-renew.sh
> Traceback (most recent call last):
> File "./noip-renew.py", line 138, in
> sys.exit(main())
> File "./noip-renew.py", line 134, in main
> robot = Robot(debug)
> File "./noip-renew.py", line 39, in **init**
> self.browser = webdriver.Chrome(chrome_options=options)
> File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 81, in **init**
> desired_capabilities=desired_capabilities)
> File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in **init**
> self.start_session(capabilities, browser_profile)
> File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
> response = self.execute(Command.NEW_SESSION, parameters)
> File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
> self.error_handler.check_response(response)
> File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
> raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.SessionNotCreatedException: Message: session not created
> from disconnected: unable to connect to renderer
> (Session info: headless chrome=74.0.3729.157)
> (Driver info: chromedriver=74.0.3729.157 (7b16107ab85c5364cdcd0b2dea2539a1f2dc327a-refs/branch-heads/3729@{#998}),platform=Linux 4.19.57-v7+ armv7l)

Can you check your /etc/hosts and verify you have an entry with 127.0.0.1 for localhost?

**Comment by sandeepan0403** [comment]
Hi 

> > I managed to get it installed on the raspberry pi 3+ however I get the following message and no error or confirmation log gets created? Anyone have the same issue?
> > pi@pivpn:~/noip/noip-renew $ sudo ./noip-renew.sh
> > Traceback (most recent call last):
> > File "./noip-renew.py", line 138, in
> > sys.exit(main())
> > File "./noip-renew.py", line 134, in main
> > robot = Robot(debug)
> > File "./noip-renew.py", line 39, in **init**
> > self.browser = webdriver.Chrome(chrome_options=options)
> > File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 81, in **init**
> > desired_capabilities=desired_capabilities)
> > File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in **init**
> > self.start_session(capabilities, browser_profile)
> > File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
> > response = self.execute(Command.NEW_SESSION, parameters)
> > File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
> > self.error_handler.check_response(response)
> > File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
> > raise exception_class(message, screen, stacktrace)
> > selenium.common.exceptions.SessionNotCreatedException: Message: session not created
> > from disconnected: unable to connect to renderer
> > (Session info: headless chrome=74.0.3729.157)
> > (Driver info: chromedriver=74.0.3729.157 (7b16107ab85c5364cdcd0b2dea2539a1f2dc327a-refs/branch-heads/3729@{#998}),platform=Linux 4.19.57-v7+ armv7l)
> 
> Can you check your /etc/hosts and verify you have an entry with 127.0.0.1 for localhost?

Hi drunkly,

I have the following in the etc/hosts
127.0.0.1       pivpn
::1             localhost ip6-localhost ip6-loopback
ff02::1         ip6-allnodes
ff02::2         ip6-allrouters

127.0.1.1       raspberrypi

There is an entry for 127.0.0.1

**Comment by drunkly** [comment]
It's just a theory but I think your problem could be related to the conflicts using ipv4/ipv6 simoultanously.

I'm seeing localhost is resolving to ::1 (ipv6).
Could you append this entry to the end of the file and try again?:
`127.0.0.1 localhost`

If this doesn't work the problem could be related to other problem like firewall preventing selenium connection to the loopback interface.

Another thing you should check is the address "127.0.0.1" is your loopback address. To do this you can run sudo ifconfig and get some interface kind of this:
```
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1  (Local Loopback)
        RX packets 216714  bytes 73803287 (70.3 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 216714  bytes 73803287 (70.3 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```
Where  "inet 127.0.0.1" is the loopback ip address for your server. If you have here other like "127.0.1.1" you should add this to your hosts:
`127.0.1.1 localhost`

**Comment by 9Mad-Max5** [comment]
I hade some othe issues. While changing python from python2 as usual to python3 for conveniece in the daily buisness python-automationhat fails to install.
It aswell corupts the apt-get functionality.
The only solution for me was to go in /usr/bin and change back the link.
`cd /usr/bin
sudo rm python
sudo ln -s python2 python
sudo apt-get upgrade`

Then the container service was back running and I could made it to run the bot.

 Afterwards I could change back python to python3.

**Comment by Modged** [comment]
Hello it doesnt work on my pi 3 can you help me ?
2019/11/17 14:10:04 [modged] - Debug level: 2
2019/11/17 14:10:04 [modged] - Open https://www.noip.com/login...
2019/11/17 14:10:06 [modged] - Message: chrome not reachable

  (Session info: headless chrome=74.0.3729.157)
  (Driver info: chromedriver=74.0.3729.157 (7b16107ab85c5364cdcd0b2dea2539a1f2dc327a-refs/branch-heads/3729@{#998}),platform=Linux 4.19.75-v7+ armv7l)

Traceback (most recent call last):
  File "./noip-renew.py", line 138, in <module>
    sys.exit(main())
  File "./noip-renew.py", line 135, in main
    return robot.run(username, password, num_hosts)
  File "./noip-renew.py", line 114, in run
    self.browser.save_screenshot("exception.png")
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 1055, in save_screenshot
    return self.get_screenshot_as_file(filename)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 1032, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 1064, in get_screenshot_as_png
    return base64.b64decode(self.get_screenshot_as_base64().encode('ascii'))
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 1074, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)['value']
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: headless chrome=74.0.3729.157)
  (Driver info: chromedriver=74.0.3729.157 (7b16107ab85c5364cdcd0b2dea2539a1f2dc327a-refs/branch-heads/3729@{#998}),platform=Linux 4.19.75-v7+ armv7l)

**Comment by 9Mad-Max5** [comment]
> I have installed on Raspberry Pi 2 (Raspbian)
> The only things I have a changed are the chromium driver (as suggested above) and selenium installation:
> sudo apt -y install chromedriver
> sudo pip install selenium
> 
> I recommend also you check pip and pip3 are installed before install selenium:
> sudo apt-get -y install pip pip3
> 
> That was all I did and it's running by now.

I think that has solved the issue.
Nevertheless noip wokrs but can´t find the button on my instance.

**Comment by Modged** [comment]
> 
> 
> > I have installed on Raspberry Pi 2 (Raspbian)
> > The only things I have a changed are the chromium driver (as suggested above) and selenium installation:
> > sudo apt -y install chromedriver
> > sudo pip install selenium
> > I recommend also you check pip and pip3 are installed before install selenium:
> > sudo apt-get -y install pip pip3
> > That was all I did and it's running by now.
> 
> I think that has solved the issue.
> Nevertheless noip wokrs but can´t find the button on my instance.

I did it ... :(

**Comment by 9Mad-Max5** [comment]
did you tried to run it by hand?

**Comment by Modged** [comment]
What do you mean ?

**Comment by 9Mad-Max5** [comment]
for me it was better installing the missing package on my own. So not using it as part of the shell. So if you tried it the manual way.

**Comment by Modged** [comment]
I did install python-pip3 python-pip chromedriver
then pip install selenium
Something else about it ?

**Comment by thangvc91** [comment]
For me , it has work with Pi3B (follow the instruction above), but
unfortunately , i dont know why it did not work with Pi3 although i tried
with the similar configuration with pi3B.

Can any advise for the configure for Pi3 ??

**Comment by farbus** [comment]
not working for me...

pi@BusnardoPi:~/noip-renew $ ./noip-renew.sh
Traceback (most recent call last):
  File "./noip-renew.py", line 138, in <module>
    sys.exit(main())
  File "./noip-renew.py", line 134, in main
    robot = Robot(debug)
  File "./noip-renew.py", line 39, in __init__
    self.browser = webdriver.Chrome(chrome_options=options)
  File "/home/pi/.local/lib/python2.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/home/pi/.local/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/home/pi/.local/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 111, in assert_process_still_running
    % (self.path, return_code)
selenium.common.exceptions.WebDriverException: Message: Service chromedriver unexpectedly exited. Status code was: 127

**Comment by loblab** [comment]
Please try the latest version (ver 0.5), as I merged the changes you mentioned.

I tested on Pi 4. Chromedriver & selenium is working.
