### ISSUE TITLE
something seems broken - script is not working any more.

### ISSUE THREAD

**Issue by requa3r0** [loblab/noip-renew#46]
Hi
Something is not working right anymore!
The script has not been working for quite a while.

The user in image debug1-2 and exeption.png looks fine. 
The script is logging in correctly and loads the correct pages.

Software:
I have cloned latest code on my debian 9 sever - user: debian

The additional Software has been a bit of a nightmare to figure out, since last update.
Mainly because i run Debian 9...so all repos are not running latest versions.
I have sideloaded all software...and this means that running setup.sh...BREALS EVERTHING!
Please change the script to ASK before installing / updating software in an installation script!
IF anwser is no...just list the software installed...and show if its ok or not!
Otherwise the installer will undo all the sideloaded software and downgrade to repo versions!!!

Anyway I have made sure all software are the newest version, and I have no code breaks due to incompatibility!

Im Running
Chromium 73.0.3683.75 built on Debian 9.8, running on Debian 9.13
ChromeDriver 87.0.4280.20
Python 3.6.4

sudo python3.6 -m pip install selenium
Requirement already satisfied: selenium in /usr/local/lib/python3.6/site-packages (3.141.0)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.6/site-packages (from selenium) (1.26.2)

Runing as user
[2020/12/28 14:36:20] - Debug level: 2
[2020/12/28 14:36:20] - Opening https://www.noip.com/login...
[2020/12/28 14:36:23] - Logging in...
[2020/12/28 14:36:23] - Incorrect padding
[sudo] password for debian: 
30 0    * * *   debian    /usr/local/bin/noip-renew-debian /var/log/noip-renew/debian

run with sudo

sudo ./noip-renew-debian         
[2020/12/28 14:55:40] - Debug level: 2
[2020/12/28 14:55:40] - Opening https://www.noip.com/login...
[2020/12/28 14:55:43] - Logging in...
[2020/12/28 14:55:53] - Opening https://my.noip.com/#!/dynamic-dns...
[2020/12/28 14:55:55] - Message: no such element: Unable to locate element: {"method":"xpath","selector":".//a[@class='text-info cursor-pointer']"}
  (Session info: headless chrome=87.0.4280.66)

30 0    * * *   debian    /usr/local/bin/noip-renew-debian /var/log/noip-renew/debian

See image of  Debug2 and exeption.png

![debug2](https://user-images.githubusercontent.com/16628002/103220920-b5eeb300-4921-11eb-9115-5ea40b7f26df.png)
![exeption](https://user-images.githubusercontent.com/16628002/103220923-b71fe000-4921-11eb-9a9f-67e5d2043fcc.png)

**Comment by loblab** [comment]
Please try the latest version which merged the fix.
