### ISSUE TITLE
Unable to install chromium-chromedriver and chromium-browser

### ISSUE THREAD

**Issue by fana13** [loblab/noip-renew#53]
Hi,

I'm on Debian Buster AMD64 and i can't install the setup.sh script.
Unable to locate chromium-chromedriver package and no version chromium-browser package is available.
The script stop after that.

Here my sources.list >

deb http://deb.debian.org/debian/ buster main
deb-src http://deb.debian.org/debian/ buster main

deb http://security.debian.org/debian-security buster/updates main
deb-src http://security.debian.org/debian-security buster/updates main

# buster-updates, previously known as 'volatile'
deb http://deb.debian.org/debian/ buster-updates main
deb-src http://deb.debian.org/debian/ buster-updates main

Can you help me please ?

**Comment by Swarsele** [comment]
chromium-browser is just called chromium for debian, update setup.sh accordingly

**Comment by fana13** [comment]
This is it !
Many thanks
