### ISSUE TITLE
"No hosts or host table rows not found"

### ISSUE THREAD

**Issue by makultar** [loblab/noip-renew#55]
[2021/02/17 Debug level: 2
[2021/02/17 Opening https://www.noip.com/login...
[2021/02/17 Logging in...
[2021/02/17 Opening https://my.noip.com/#!/dynamic-dns...
[2021/02/17 No hosts or host table rows not found

Any idea? I do have a hostname, which is waiting to get confirmed when logging in.

**Comment by makultar** [comment]
I run "bash noip-renew.sh"

**Comment by freeman-pl** [comment]
Have you use? 
noip-renew-your-user.sh

Dnia 17 lutego 2021 16:01:28 CET, makultar <notifications@github.com> napisał(a):
>[2021/02/17 Debug level: 2
>[2021/02/17 Opening https://www.noip.com/login...
>[2021/02/17 Logging in...
>[2021/02/17 Opening https://my.noip.com/#!/dynamic-dns...
>[2021/02/17 No hosts or host table rows not found
>
>Any idea? I do have a hostname, which is waiting to get confirmed when
>logging in.

**Comment by makultar** [comment]
> noip-renew-your-user.sh

Thanks for your quick reply!! Very kind.
Well I am only running "`bash noip-renew.sh`" which then seem to execute the python script `noip-renew.py` which logs in using the configured username & password which I have entered during `bash setup.sh`.

**Comment by freeman-pl** [comment]
If you install script and add noip account properly try to use
noip-renew-your_system_user_here.sh

 you don't enter user that create create install a script that's why you get no host info

**Comment by makultar** [comment]
> If you install script and add noip account properly try to use
> noip-renew-your_system_user_here.sh
> 
> you don't enter user that create create install a script that's why you get no host info


I love you!
noip-renew-linuxusername.sh worked!!!! THANKS!!!!!!!!!!!!!!!!!!!
