### ISSUE TITLE
"Chrome version must be between 70 and 73" error

### ISSUE THREAD

**Issue by requa3r0** [loblab/noip-renew#6]
Hi. I get the following errors when running manually.

The script has been running flawless until 21 juni 2019, where it stopped working according to my log.
I did check noip.com..and i believe I had a CAPTCHA test, but I don't have that anymore on the web interface. Must have been on VPN or something to trigger the CAPTCHA. 

I'm doing the update manually now, and its really annoying. I love the noip-renew script.

`root@xxxxxx:/usr/local/bin# ./noip-renew-debian
Traceback (most recent call last):
  File "./noip-renew.py", line 138, in <module>
    sys.exit(main())
  File "./noip-renew.py", line 134, in main
    robot = Robot(debug)
  File "./noip-renew.py", line 39, in __init__
    self.browser = webdriver.Chrome(chrome_options=options)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome version must be between 70 and 73
  (Driver info: chromedriver=73.0.3683.75,platform=Linux 4.9.0-3-amd64 x86_64)
`

The renew script has stopped working as you can see, and it ends issuing a error message, that "Chrome version must be between 70 and 73"

I have verified my chormedriver ...as pasted below.

`root@xxxxxxxx:/usr/local/bin# chromedriver -v
ChromeDriver 73.0.3683.75
root@xxxxxxxxx:/usr/local/bin# apt-get install chromedriver
Reading package lists... Done
Building dependency tree       
Reading state information... Done
chromedriver is already the newest version (73.0.3683.75-1~deb9u1).
0 upgraded, 0 newly installed, 0 to remove and 23 not upgraded.
root@xxxxxxxxx:/usr/local/bin# `

What is wrong?
requa3r0

**Comment by requa3r0** [comment]
Can anyone confirm that the script still works?

**Comment by requa3r0** [comment]
for info.  chromium / ChromeDriver 73.0.3683.75  DOES NOT WORK

Run
apt-get purge chromium
apt-get purge ChromeDriver 
apt-get autoremove

Make sure all is goon!

Then install verion 70.xxx

apt-get install chromium=70.0.3538.110-1~deb9u1
apt-get install chromedriver=70.0.3538.110-1~deb9u1

Then all is good ;O) 

The script logs ind and checks as normal.

debian@xxxxxxxx:~/Downloads/noip-renew-master$ sudo apt-get install chromium=70.0.3538.110-1~deb9u1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
chromium is already the newest version (70.0.3538.110-1~deb9u1).
0 upgraded, 0 newly installed, 0 to remove and 21 not upgraded.


debian@xxxxxxx:~/Downloads/noip-renew-master$ sudo apt-get install chromium-driver=70.0.3538.110-1~deb9u1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
chromium-driver is already the newest version (70.0.3538.110-1~deb9u1).
0 upgraded, 0 newly installed, 0 to remove and 21 not upgraded.


debian@xxxxxxxxx:~/Downloads/noip-renew-master$ /./usr/local/bin/noip-renew-debian
2019/12/12 23:14:17 [xxx] - Debug level: 2
2019/12/12 23:14:17 [xxx] - Open https://www.noip.com/login...
2019/12/12 23:14:21 [xxx] - Login...
2019/12/12 23:14:28 [xxx] - Open https://my.noip.com/#!/dynamic-dns...
2019/12/12 23:14:29 [xxx] - Hosts to be confirmed: 0
2019/12/12 23:14:30 [xxx] - Confirmed hosts: 0

**Comment by requa3r0** [comment]
I had some issues downgrading..from 73 to 70..it simply refuses.
solusion is to disable some security updates in sorces.list

I also locked the verion to 70 in synaptic manager.

This worked

onlu run with first 2 lines with / strech main

deb http://ftp.dk.debian.org/debian/ stretch main
deb-src http://ftp.dk.debian.org/debian/ stretch main

#deb http://security.debian.org/debian-security stretch/updates main
#deb-src http://security.debian.org/debian-security stretch/updates main

# stretch-updates, previously known as 'volatile'
#deb http://ftp.dk.debian.org/debian/ stretch-updates main
#deb-src http://ftp.dk.debian.org/debian/ stretch-updates main

**Comment by loblab** [comment]
As mentioned in #8, adding this line seems work.
```bash
options.add_argument('--disable-features=VizDisplayCompositor')
```

I cannot connect noip.com without VPN. However, chromedriver is working I think.

![image](https://user-images.githubusercontent.com/11693722/71782043-6f1cf480-3010-11ea-8de0-1a1e9b3b7503.png)
