### ISSUE TITLE
Ubuntu server 18.04

### ISSUE THREAD

**Issue by abdelilahxq** [loblab/noip-renew#7]
please support ubuntu server 18.04

**Comment by requa3r0** [comment]
If you read my comments about chromedriver... And downgrade...accordingly. Why should it not work?

**Comment by abdelilahxq** [comment]
sorry i don't read comments about chromedriver i try now thank you

**Comment by abdelilahxq** [comment]
sudo ./noip-renew.sh 
Traceback (most recent call last):
  File "./noip-renew.py", line 16, in <module>
    from selenium import webdriver
ImportError: No module named selenium

**Comment by requa3r0** [comment]
1 
you have not installed  noip-renew correctly
run the setup.sh after setting up user and password and number of domains.
you file is not in /use/local/bin/USERNAME

dont run the setup.sh as root..but as your standard linux  UISER...

2
After that make sure to downgrade to chromium and chromedriver 70.xxx i dont know the precise version for ubunu..but look at my post for debian..and google what old-stable is avaiable for ubunto server 18. Then downgrade to this.

**Comment by abdelilahxq** [comment]
i edit script setup.sh the line 28     
from 

$SUDO apt -y install chromedriver

to 

$SUDO apt -y install chromium-chromedriver

abdo@abdo:~/no/noip-renew$sudo vim setup.sh
................................

 26 function install() {
 27     echo "Install necessary packages..."
 28     $SUDO apt -y install chromium-chromedriver
 29     #$SUDO apt -y install chromedriver
 30     # Debian9 package 'python-selenium' does not work with chromedriver,
 31     # Install from pip, which is newer
 32     $SUDO apt -y install $PYTHON-pip
 33     $SUDO $PYTHON -m pip install selenium
 34 }
................................

abdo@abdo:~/no/noip-renew$ ./setup.sh 
Install necessary packages...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
chromium-chromedriver is already the newest version (79.0.3945.79-0ubuntu0.18.04.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-pip is already the newest version (9.0.1-2.3~ubuntu1.18.04.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: selenium in /usr/local/lib/python3.6/dist-packages
Requirement already satisfied: urllib3 in /usr/lib/python3/dist-packages (from selenium)
Deploy the script (run twice every week)...
45 3    * * 1,3,5   abdo    /usr/local/bin/noip-renew-abdo /var/log/noip-renew/abdo
Done.
Please confirm the account info in '/usr/local/bin/noip-renew-abdo'
Also check logs in '/var/log/noip-renew/abdo' after running the cron job

abdo@abdo:~/no/noip-renew$ /usr/local/bin/noip-renew-abdo 
Traceback (most recent call last):
  File "/usr/local/bin/noip-renew.py", line 16, in <module>
    from selenium import webdriver
ImportError: No module named selenium

abdo@abdo:~/no/noip-renew$ ll /usr/local/bin/noip-renew-abdo 
-rwx------ 1 abdo root 407 Dec 23 14:38 /usr/local/bin/noip-renew-abdo*

abdo@abdo:~/no/noip-renew$ whereis chromedriver
chromedriver: /usr/bin/chromedriver

abdo@abdo:~/no/noip-renew$ which chromedriver
/usr/bin/chromedriver

abdo@abdo:~/no/noip-renew$ chromedriver -v
ChromeDriver 79.0.3945.79 (29f75ce3f42b007bd80361b0dfcfee3a13ff90b8-refs/branch-heads/3945@{#916})

abdo@abdo:~/no/noip-renew$ sudo apt search chromedriver
Sorting... Done
Full Text Search... Done
chromium-chromedriver/bionic-updates,bionic-security,bionic,now 79.0.3945.79-0ubuntu0.18.04.1 amd64 [installed]
  WebDriver driver for the Chromium Browser

abdo@abdo::~/no/noip-renew$ sudo apt search chromium
Sorting... Done
Full Text Search... Done
browser-plugin-freshplayer-pepperflash/bionic-updates 0.3.9-0ubuntu0.18.04.1 amd64
  PPAPI-host NPAPI-plugin adapter for pepperflash

cgpt/bionic 0~R63-10032.B-3 amd64
  GPT manipulation tool with support for Chromium OS extensions

chrome-gnome-shell/bionic 10-1 all
  GNOME Shell extensions integration for web browsers

chromium/now 70.0.3538.110-1~deb9u1 amd64 [residual-config]
  (none)

chromium-browser/bionic-updates,bionic-security,bionic,now 79.0.3945.79-0ubuntu0.18.04.1 amd64 [installed,automatic]
  Chromium web browser, open-source version of Chrome

chromium-browser-l10n/bionic-updates,bionic-security,bionic,now 79.0.3945.79-0ubuntu0.18.04.1 all [installed,automatic]
  chromium-browser language packages

chromium-bsu/bionic 0.9.16.1-1 amd64
  fast paced, arcade-style, scrolling space shooter

chromium-bsu-data/bionic 0.9.16.1-1 all
  data pack for the Chromium B.S.U. game

chromium-chromedriver/bionic-updates,bionic-security,bionic,now 79.0.3945.79-0ubuntu0.18.04.1 amd64 [installed]
  WebDriver driver for the Chromium Browser

chromium-codecs-ffmpeg/bionic-updates,bionic-security,bionic 79.0.3945.79-0ubuntu0.18.04.1 amd64
  Free ffmpeg codecs for the Chromium Browser

chromium-codecs-ffmpeg-extra/bionic-updates,bionic-security,bionic,now 79.0.3945.79-0ubuntu0.18.04.1 amd64 [installed,automatic]
  Extra ffmpeg codecs for the Chromium Browser

chromium-lwn4chrome/bionic 1.0-2 all
  Chromium extension for making LWN.net slightly easier to read

chromium-tt-rss-notifier/bionic 0.5.2-1 all
  Chromium extension providing toolbar button for TT-RSS installations

chromium-ublock-origin/bionic 1.13.8+dfsg-1 all
  general-purpose lightweight ads, malware, trackers blocker (Chromium)

emacs-mozc/bionic-updates 2.20.2673.102+dfsg-2ubuntu0.18.04.1 amd64
  Mozc for Emacs

emacs-mozc-bin/bionic-updates 2.20.2673.102+dfsg-2ubuntu0.18.04.1 amd64
  Helper module for emacs-mozc

flashplugin-installer/bionic-updates,bionic-security 32.0.0.303ubuntu0.18.04.2 amd64
  Adobe Flash Player plugin installer

goopg/bionic 0.3.1-9 all
  GPG for Chromium GMail

ibus-mozc/bionic-updates 2.20.2673.102+dfsg-2ubuntu0.18.04.1 amd64
  Mozc engine for IBus - Client of the Mozc input method

icedtea-8-plugin/bionic-updates,bionic-security 1.8-0ubuntu8~18.04 amd64
  web browser plugin based on OpenJDK and IcedTea to execute Java applets

icedtea-plugin/bionic-updates,bionic-security 1.8-0ubuntu8~18.04 all
  web browser plugin to execute Java applets (dependency package)

libv8-3.14-dbg/bionic 3.14.5.8-11ubuntu1 amd64
  V8 JavaScript engine - debugging symbols

libv8-3.14-dev/bionic 3.14.5.8-11ubuntu1 amd64
  V8 JavaScript engine - development files for 3.14 branch

libv8-3.14.5/bionic 3.14.5.8-11ubuntu1 amd64
  V8 JavaScript engine - runtime library

libv8-dev/bionic 3.14.5.8-11ubuntu1 amd64
  V8 JavaScript engine - development files for latest branch

mozc-data/bionic-updates 2.20.2673.102+dfsg-2ubuntu0.18.04.1 all
  Mozc input method - data files

mozc-server/bionic-updates 2.20.2673.102+dfsg-2ubuntu0.18.04.1 amd64
  Server of the Mozc input method

mozc-utils-gui/bionic-updates 2.20.2673.102+dfsg-2ubuntu0.18.04.1 amd64
  GUI utilities of the Mozc input method

ninja-build/bionic 1.8.2-1 amd64
  small build system closest in spirit to Make

node-electron-to-chromium/bionic 1.3.21-1 all
  Provides a list of electron-to-chromium version mappings

pepperflashplugin-nonfree/bionic 1.8.3+nmu1ubuntu1 amd64
  Pepper Flash Player - browser plugin

python-libnacl/bionic 1.6.1-3 all
  Python 2 bindings for libsodium based on ctypes

python-pyftpdlib/bionic 1.5.1-4ubuntu1 all
  Python FTP server library

python-pyqt5.qtwebengine/bionic 5.10.1+dfsg-1ubuntu2 amd64
  Python 2 bindings for Qt5's WebEngine module

python-pyqt5.qtwebengine-dbg/bionic 5.10.1+dfsg-1ubuntu2 amd64
  Python 2 bindings for Qt5's WebEngine module (debug extensions)

python3-libnacl/bionic 1.6.1-3 all
  Python 3 bindings for libsodium based on ctypes

python3-pyftpdlib/bionic 1.5.1-4ubuntu1 all
  Python FTP server library

python3-pyqt5.qtwebengine/bionic 5.10.1+dfsg-1ubuntu2 amd64
  Python 3 bindings for Qt5's WebEngine module

python3-pyqt5.qtwebengine-dbg/bionic 5.10.1+dfsg-1ubuntu2 amd64
  Python 3 bindings for Qt5's WebEngine module (debug extensions)

uim-mozc/bionic-updates 2.20.2673.102+dfsg-2ubuntu0.18.04.1 amd64
  Mozc engine for uim - Client of the Mozc input method

unity-scope-chromiumbookmarks/bionic 0.1+13.10.20130723-0ubuntu1 all
  Chromium bookmarks scope for Unity

webext-browserpass/bionic 2.0.11+dfsg-2 amd64
  web extension for the password manager pass

**Comment by loblab** [comment]
@abdelilahxq yes, the package name is different.

As I tested:
- Raspbian: chromium-chromedriver
- Ubuntu 18.04 (server): chromium-driver
- Ubuntu 19.10 (desktop): chromium-chromedriver

So I simply try everyone in setup.sh in the latest version.

**Comment by abdelilahxq** [comment]
Thank you, I've worked 
i use this script to Install Chrome, ChromeDriver and Selenium on Ubuntu 16.04 and Ubuntu 18.04 (server)
https://gist.github.com/ziadoz/3e8ab7e944d02fe872c3454d17af31a5
