### ISSUE TITLE
Install on Raspberry Pi

### ISSUE THREAD

**Issue by lorenzoracca** [loblab/noip-renew#8]
In order to install the script on Raspberry Pi, in addition to the original, follow these steps:

1. Install Selenium since the script does not do so automatically with 
`sudo pip install selenium`

2. Edit the noip-renew.sh file by changing all occurrences of `chromedriver` into `chromium-chromedriver`

3. As of the moment, chromium on Raspbian Buster+ versions does not work without adding the code `options.add_argument('--disable-features=VizDisplayCompositor')` to `noip-renew.py` among all the other options under `__init__` . Check https://www.raspberrypi.org/forums/viewtopic.php?t=258019 for reference. 
Running the script without doing step 3 will throw a "Chrome not reachable" error.

**Comment by loblab** [comment]
Great. Thank you. I merged the changes.

And, the package names of "chromedriver" are different as I tested:
- Raspbian: chromium-chromedriver
- Ubuntu 18.04 (server): chromium-driver
- Ubuntu 19.10 (desktop): chromium-chromedriver

So I simply try everyone in setup.sh
